import type { AuditEvent } from './audit-event';

/** Nome de cada evento para o relatório de auditoria (RN-REP-08). Todo evento precisa de um. */
export const AUDIT_EVENT_LABEL: Readonly<Record<AuditEvent, string>> = {
  LOGIN: 'Entrou no sistema',
  LOGIN_FAILED: 'Tentativa de entrada recusada',
  LOGOUT: 'Saiu do sistema',
  USER_CREATED: 'Usuário cadastrado',
  USER_UPDATED: 'Usuário alterado',
  USER_DISABLED: 'Usuário desativado',
  ROLE_CHANGED: 'Perfil alterado',
  COMPANY_CREATED: 'Empresa cadastrada',
  COMPANY_UPDATED: 'Empresa alterada',
  STORE_CREATED: 'Loja cadastrada',
  STORE_UPDATED: 'Loja alterada',
  STORE_DISABLED: 'Loja desativada',
  STORE_ENABLED: 'Loja reativada',
  STORE_SWITCHED: 'Troca de loja',
  TERMINAL_CREATED: 'Terminal cadastrado',
  TERMINAL_UPDATED: 'Terminal alterado',
  TERMINAL_DISABLED: 'Terminal desativado',
  TERMINAL_ENABLED: 'Terminal reativado',
  TERMINAL_BOUND: 'Aparelho vinculado ao terminal',
  TERMINAL_UNBOUND: 'Aparelho desvinculado do terminal',
  CATEGORY_CREATED: 'Categoria do cardápio cadastrada',
  CATEGORY_UPDATED: 'Categoria do cardápio alterada',
  PRODUCT_CREATED: 'Produto cadastrado',
  PRODUCT_UPDATED: 'Produto alterado',
  PRODUCT_DISABLED: 'Produto desativado',
  PRODUCT_ENABLED: 'Produto reativado',
  PRODUCT_PRICE_SET: 'Preço definido',
  PRODUCT_REMOVED_FROM_STORE: 'Produto retirado da loja',
  PRODUCT_AVAILABILITY_CHANGED: 'Disponibilidade alterada',
  MODIFIER_GROUP_CREATED: 'Grupo de adicionais cadastrado',
  MODIFIER_GROUP_UPDATED: 'Grupo de adicionais alterado',
  MODIFIER_CREATED: 'Adicional cadastrado',
  MODIFIER_UPDATED: 'Adicional alterado',
  ORDER_OPENED: 'Conta aberta',
  ORDER_ITEM_ADDED: 'Item lançado',
  ORDER_ITEM_CANCELLED: 'Item cancelado',
  ORDER_CLOSED: 'Conta fechada',
  ORDER_CANCELLED: 'Conta cancelada',
  TABLE_TRANSFERRED: 'Mesa transferida',
  DISCOUNT_APPLIED: 'Desconto aplicado',
  SERVICE_FEE_REMOVED: 'Taxa de serviço retirada',
  ELEVATED_AUTH_GRANTED: 'Autorização do gerente',
  PAYMENT_CREATED: 'Pagamento recebido',
  PAYMENT_CANCELLED: 'Pagamento estornado',
  CASH_OPENED: 'Caixa aberto',
  CASH_MOVEMENT: 'Sangria ou suprimento',
  CASH_CLOSED: 'Caixa fechado',
  CASH_RECOUNT_REQUESTED: 'Recontagem do dinheiro pedida no fechamento',
  INGREDIENT_CREATED: 'Insumo cadastrado',
  INGREDIENT_UPDATED: 'Insumo alterado',
  STOCK_MINIMUM_SET: 'Estoque mínimo definido',
  STOCK_ENTRY: 'Entrada de estoque',
  STOCK_EXIT: 'Saída de estoque',
  STOCK_ADJUSTMENT: 'Ajuste de estoque',
  STOCK_LOSS: 'Perda de estoque',
  RECIPE_UPDATED: 'Ficha técnica alterada',
  TABLE_CREATED: 'Mesa cadastrada',
  TABLE_UPDATED: 'Mesa alterada',
  TABLE_STATUS_CHANGED: 'Situação da mesa alterada',
  TABLE_DETACHED: 'Mesa separada',
  ORDER_ROUND_SENT: 'Pedido enviado à cozinha',
  ORDERS_MERGED: 'Contas juntadas',
  KITCHEN_READY_UNDONE: 'Pronto desfeito na cozinha',
  PRE_BILL_ISSUED: 'Pré-conta emitida',
  SERVICE_FEE_RESTORED: 'Taxa de serviço devolvida',
  FINANCE_CATEGORY_CREATED: 'Categoria financeira criada',
  FINANCE_CATEGORY_UPDATED: 'Categoria financeira alterada',
  FINANCE_ENTRY_CREATED: 'Lançamento financeiro criado',
  FINANCE_ENTRY_PAID: 'Lançamento financeiro pago',
  FINANCE_ENTRY_CANCELLED: 'Lançamento financeiro cancelado',
};
